version: '3.3'
services:
    app:
        build: ./app
        links:
            - db
        volumes:
            - ./app/data:/data
        ports:
            - "5000:5000" 
    db:
        image: mysql:latest
        volumes:
            - ./db:/docker-entrypoint-initdb.d/:ro
        environment:
            MYSQL_ROOT_PASSWORD: root
            #MYSQL_ROOT_HOST 192.168.99.1
            MYSQL_DATABASE: mydb
            MYSQL_USER: user
            MYSQL_PASSWORD: pass
        ports:
        #192.168.99.101
            - "3306:3306"

