version: '3.3'
services:
    db:
        #container_name: mysql_db
        image: mysql:latest
        container_name: mysqldb
        volumes:
            - "./informatica_data/database:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_ROOT_HOST: 192.168.99.1
            MYSQL_DATABASE: mydb
            MYSQL_USER: user
            MYSQL_PASSWORD: pass
        ports:
        #192.168.99.101
            - "3306:3306"